spring.application.name=greenated

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/greenated
spring.datasource.username=root
spring.datasource.password=zoondia

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret:59703373367639792F423F4528482B4D6251655468576D5A71347437


code.success: -1
code.fail: 449
code.error.bad-request: 400
code.error.service-error: 500
running.environment: ${ENVIRONMENT}

message.success: Successfully Completed
message.fail: Failed
message.error.bad-request: Resource Requested Not Available
message.error.service-error: Something Went Wrong, Try Later