spring.application.name=greenated
server.port=8080

jwt.secret=59703373367639792F423F4528482B4D6251655468576D5A71347437

code.success=-1
code.fail=449
code.error.bad-request=400
code.error.service-error=500

message.success=Successfully Completed
message.fail=Failed
message.error.bad-request=Resource Requested Not Available
message.error.service-error=Something Went Wrong, Try Later

running.environment=dev